// <auto-generated />
using Fate.EfContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace Fate.API.Migrations
{
    [DbContext(typeof(EntityDbContext))]
    [Migration("20180820083231_newusers820")]
    partial class newusers820
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Models.Users.UserInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(100);

                    b.Property<string>("Company")
                        .HasMaxLength(100);

                    b.Property<string>("Name");

                    b.Property<string>("Phone")
                        .HasColumnName("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .HasColumnName("UserName")
                        .HasMaxLength(20);

                    b.Property<string>("UserPassword")
                        .HasColumnName("UserPassword")
                        .HasMaxLength(20);

                    b.HasKey("ID");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("Models.Users.UserTags", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnName("Tag")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnName("datetime");

                    b.HasKey("UserId", "Tag");

                    b.ToTable("UserTags");
                });
#pragma warning restore 612, 618
        }
    }
}
